### ISSUE TITLE
ERR unknown command 'REDISQL.CREATE_DB'

### ISSUE THREAD

**Issue by mijklgps** [RedBeardLab/JRediSQL#3]
i clone your  code , but i can not run it correct.
---
```
redis.clients.jedis.exceptions.JedisDataException: ERR unknown command 'REDISQL.CREATE_DB'

	at redis.clients.jedis.Protocol.processError(Protocol.java:131)
	at redis.clients.jedis.Protocol.process(Protocol.java:165)
	at redis.clients.jedis.Protocol.read(Protocol.java:219)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:309)
	at redis.clients.jedis.Connection.getBinaryBulkReply(Connection.java:255)
	at redis.clients.jedis.Connection.getBulkReply(Connection.java:245)
	at com.redbeardlab.redisql.client.RediSQLClient.ok_returns(RediSQLClient.java:89)
	at com.redbeardlab.redisql.client.RediSQLClient.create_db(RediSQLClient.java:98)
	at com.redbeardlab.redisql.client.RediSQLClientTest.creatingDatabaseWorks(RediSQLClientTest.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:532)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:115)
```
---
i use the redis-cli is all ok

![image](https://user-images.githubusercontent.com/16040953/89159506-29bea680-d5a2-11ea-921a-3089ead8cbc3.png)

**Comment by siscia** [comment]
Hello,

Sorry at the moment I am not in the office. I will be back late next week.

I will have a look but it will take some time.

My suggestion is to you to work through the issue yourself, it will be simpler.

Maybe I am wrong but I created a maven package for this, didn't I?

Maybe it is simpler with the package...
